New Local Notification Sample port from Legacy
xamarin/monodroid-samples pull request #341
Opened 2022-07-12 23:06 UTC by officialgio

2022-07-13 00:08 UTC, tj-devel709 requested changes
Great Start! Few suggestions and questions

2022-07-13 00:08 UTC, tj-devel709 commented on LocalNotifications/LocalNotifications/SecondActivity.cs
> +        if (count <= 0)
Does this have any nullability issues?

2022-07-13 00:08 UTC, tj-devel709 commented on LocalNotifications/LocalNotifications/MainActivity.cs
> +
```suggestion
```

2022-07-13 15:54 UTC, officialgio commented on LocalNotifications/LocalNotifications/MainActivity.cs
> +        // API 26 and below works but are new in API 26+
I've modified the comment.

2022-07-13 15:58 UTC, officialgio commented on LocalNotifications/LocalNotifications/MainActivity.cs
> +        ArgumentNullException.ThrowIfNull(Resources);
Done!

2022-07-13 15:59 UTC, officialgio commented on LocalNotifications/LocalNotifications/MainActivity.cs
> +
Done!

2022-07-14 18:09 UTC, rachelkang reviewed
I wasn't able to get the notifications working on my device with API 32, but apparently it's working fine on API 31. @jonathanpeppers do you have any ideas?

2022-07-15 20:21 UTC, jonathanpeppers commented
@rachelkang do we need to add this:

https://developer.android.com/about/versions/13/changes/notification-permission

```xml
<uses-permission android:name="android.permission.POST_NOTIFICATIONS"/>
```

2022-12-19 17:13 UTC, jonathanpeppers approved these changes

2022-12-19 17:13 UTC, merged